### ISSUE TITLE
When should we consider using Flux?

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/MoFo-Engineering-Handbook#43]
Advice i got from @dmose was to do so before the app got too complex.  Probably worth @Pomax or someone getting a bit familiar w/ it.

**Comment by dmose** [comment]
Yes.  @n1k0 and @Standard8 did most of the work to untangle our pre-Flux architecture into Flux stuff, and it made things significantly more comprehensible at scale.  It's easy enough to start with Flux.  There may still be some things being sorted out w.r.t. error-handling in stores (with the Flux architecture in general) I think @n1k0 may have some thoughts there.

**Comment by dmose** [comment]
Note that we rolled our own Flux implementation, and it seems to be working well enough.  Flux as described by Facebook is a bit boilerplate-y, and reflux addresses some of that, but it changes some semantics too in ways that might (or might not) be problematic (eg its dispatcher doesn't force serialization, which seems like it might not prevent races the way forcing serialization would).

**Comment by toolness** [comment]
I'm looking into Flux now as our [teach](https://github.com/mozilla/teach.webmaker.org) site grows. Facebook's [Flux website](https://facebook.github.io/flux/) repeatedly states that it's really more of an architecture or "way of doing things" than a framework or library of reusable code. In fact, the only thing you really get when you `npm install flux` is the dispatcher. Which honestly makes me feel a bit relieved.

It also sorta implies that each one of our projects can implement Flux in a way that's most suitable for its particular context, rather than having to reuse and update a shared library of code--i.e. it's the shared *vocabulary* of Action/Dispatcher/Store/View and the way those nouns interact that's most important.

Another actual library of reusable code that Flux brought to my attention is [immutable JS](http://facebook.github.io/immutable-js/), which looks cool.

**Comment by Standard8** [comment]
I case folks missed it, I did a blog post a while back on Loop's use of flux and react:

https://blog.mozilla.org/standard8/2015/02/09/firefox-hello-desktop-behind-the-scenes-flux-and-react/

I see flux more as a methodology - especially when we first started the general word was that for flux there wasn't a standardised implementation/format, so as you say, its the vocabulary and the interactions that are important parts.
