### ISSUE TITLE
Discussion: What are the best "Learning React" resources?

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/MoFo-Engineering-Handbook#48]

**Comment by Pomax** [comment]
first and absolutely foremost: The React [intro](http://facebook.github.io/react/docs/getting-started.html) and [tutorial](http://facebook.github.io/react/docs/tutorial.html) on the react website itself.

If you turn off your IRC, twitters, facebooks, megaspaces and redditalls and just dedicate an hour of your life to simply open a terminal, open an editor, and follow the instructions, without going online to vent or ask questions until you're done (because most questions you have are answered after you got that question while doing the next step in the tutorials, and venting while you're doing something makes your brain establish that the thing you're venting about is shit. Hurray for cog.psy.) you already did about 85% of the work towards becoming fluent in React.

**Comment by toolness** [comment]
Regarding not going online to vent etc, I found the blog post linked-to from one of the official docs/blogs, [Give it Five Minutes](https://signalvnoise.com/posts/3124-give-it-five-minutes), to be quite helpful. Specifically when asked to use JSX, which triggered me in various ways. :) I gave it five minutes and then a little more and then I fell in love with it.

**Comment by toolness** [comment]
I agree that the React intro and tutorial are really well-written, and also help convey the whole philosophy behind React--they are also great at communicating some optional best practices, like the use of [`PureRenderMixin`](https://facebook.github.io/react/docs/pure-render-mixin.html) whenever possible.

Until it becomes part of the official react docs, I also recommend reading [Introduction to contexts in React.js](https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html) after the intro, tutorial, and a bit of real-world React experience. Contexts are currently unstable in React, and therefore undocumented, but they're planned for 1.0 and `react-router` uses them, as well as a few parts of the Teach site.
